stages:
  - performance:
    - os=centos os_version=7 os_mount=nfs os_arch=x86_64 sysbench-cpu.yaml
    - os=centos os_version=7 os_mount=nfs os_arch=x86_64 sysbench-memory.yaml
    - os=centos os_version=7 os_mount=nfs os_arch=x86_64 sysbench-mutex.yaml
    - os=centos os_version=7 os_mount=nfs os_arch=x86_64 sysbench-threads.yaml
    - os=centos os_version=7 os_mount=nfs os_arch=x86_64 sysbench-threads-git.yaml

