stages:
  - performance:
    - runtime=60 nr_threads=1 sysbench-cpu.yaml
    - runtime=60 nr_threads=1 sysbench-memory.yaml
    - runtime=60 nr_threads=1 sysbench-mutex.yaml
    - runtime=60 nr_threads=1 sysbench-threads.yaml
    - runtime=60 nr_threads=1 sysbench-threads-git.yaml
